items:
  facebook:
    id: 1001
    meta: 0
    namespace: "custom:facebook"
    name: facebook
    allow_off_hand: true
    max_stack_size: 64
    texture: ccc
    durable: true
    max_durability: 64
    mining_speed: 10