items:
  ccc:
    id: 1001
    meta: 0
    namespace: "custom:ccc"
    name: ccc
    allow_off_hand: true
    max_stack_size: 64
    texture: ccc
    durable: true
    max_durability: 64
    mining_speed: 10