on: [push, pull_request]
name: Test
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: nxtlvlsoftware/pmmp-phpstan:master
      - name: PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan:master
        with:
          args: analyse src/